### ISSUE TITLE
Access token "0" valides

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#11]
When an access token is revoked it is set to "0" ([here](https://github.com/Wadpam/guja/blob/master/guja-core/src/main/java/com/wadpam/guja/oauth2/api/OAuth2AuthorizationResource.java#L281)). But the access token validation will happily validate an access token even if it's "0" ([here](https://github.com/Wadpam/guja/blob/master/guja-core/src/main/java/com/wadpam/guja/oauth2/web/OAuth2Filter.java#L152)).

Thus, as soon as an access token has been revoked you can use access token "0" to gain access.

**Comment by mattiaslevin** [comment]
Fixed.

**Comment by peoplesbeer** [comment]
Great! I was wondering if there was a reason that it was set to 0 and not null (that's why I didn't want to do it myself), but then it wasn't I guess...

**Comment by mattiaslevin** [comment]
Lets see if Ola thinks the same.

**Comment by sosandstrom** [comment]
Please check what `revoke` should mean - I am not sure the client should be able to refresh a revoked token, as revoke perhaps should be interpreted as `I no longer want that app to access my data`.

**Comment by peoplesbeer** [comment]
When it comes to revoking access tokens you actually get to choose if you also want to revoke the refresh token or not.

> Depending on the authorization server's revocation policy, the
> revocation of a particular token may cause the revocation of related
> tokens and the underlying authorization grant.  If the particular
> token is a refresh token and the authorization server supports the
> revocation of access tokens, then the authorization server SHOULD
> also invalidate all access tokens based on the same authorization
> grant (see Implementation Note).  If the token passed to the request
> is an access token, the server MAY revoke the respective refresh
> token as well.

**Comment by mattiaslevin** [comment]
Current implementation
-If the user revoke the access token the Connection entity and this refresh token will still be kept (only the access token will be set to null)
-If the user revoke the refresh token the Connection entity will be delete (thus removing both access and refresh token)
-We only have one access token per refresh token.

The standard just tells us that we MAY remove the refresh token when invalidating the access token, up to us to decide.

My feeling is that we should go for the MAY option delete the full Connection entity when revoking the access token (this is what you expect in most cases anyway when you sign out).
Anyone disagree?

**Comment by sosandstrom** [comment]
I agree, let's close this issue :+1:
