### ISSUE TITLE
Extend the @Crud annotation to include the type or CRUD operation being performed

### ISSUE THREAD

**Issue by mattiaslevin** [Wadpam/guja#12]
Extend the @Crud annotation to include the type or CRUD operation being performed
-CREATE
-READ
-UPDATE
-DELETE

The cache method interceptor should use this value to decide if the cache should updates or invalidated when an annotated method is run.

This feature is needed when caching on something else then the entity id.

**Comment by sosandstrom** [comment]
We should consider using JSR-107 javax.cache annotations:
[https://github.com/jsr107/jsr107spec/blob/master/src/main/java/javax/cache/annotation/]

* @CacheResult on read methods
* @CachePut on create/update methods
* @CacheRemove on delete methods

I also like the idea of being able to specify the CacheKeyGenerator class.

**Comment by mattiaslevin** [comment]
There is even a Guice model implementation by the JSR group.
https://github.com/jsr107/RI/tree/master/cache-annotations-ri

My only concern is that its a lot of code. Do we need all of it. We need a solution fast and I do not have time to walkthrough what they have done.

I have finished the implementation already and currently doing final unit tests. 

I should probably change the annotations to JSR-107. We can then pull in the JSR implementation at a later stage when there is more time without affecting existing code?

What do you think?

**Comment by sosandstrom** [comment]
I was only thinking using the annotations, not the implementation.

**Comment by mattiaslevin** [comment]
Hum, understand that after going through their implementation. They even state it should not be used in production.

But they have some interesting ideas and I will bring over some parts:
-The annotations
-KeyGenerator
-CacheResolver

I will have a suggestion in a day or two

**Comment by mattiaslevin** [comment]
Ok, I made a very light-weigt JSR107 annotation implementation.

It support
@CacheDefaults
@CachePut
@CacheResure
@CacheRemove
@CacheRemoveAll
@CacheValue (cache the parameter that should be cached)
@CacheKey (cache parameters that should be used when generating the cache key)

There is also support CacheKeyGenerator on method and class level.

I will make a matching update in Mardao and send for review.

**Comment by sosandstrom** [comment]
Sounds great! :+1:

**Comment by mattiaslevin** [comment]
Fixed.
