### ISSUE TITLE
The access token request does not conform to standard

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#13]
The access token request is not done according to the OAuth 2.0 standard. It should be using the "application/x-www-form-urlencoded" content type. Submitting an access token request with that content type results in an Internal Server Error (using json works).

>The client makes a request to the token endpoint by adding the
>following parameters using the "application/x-www-form-urlencoded"...

http://tools.ietf.org/html/rfc6749#section-4.3.2

**Comment by mattiaslevin** [comment]
That is correct.

I will continue with JSON body since it feels more modern. Maybe I will add support for form-encoded body for all oauth methods in the future (but still keep JSON)

**Comment by mattiaslevin** [comment]
Fixed.
