### ISSUE TITLE
Failed access token responses are missing the WWW-Authenticate header

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#14]
Failed access token responses are missing the ``WWW-Authenticate`` header.

>If the protected resource request does not include authentication
>credentials or does not contain an access token that enables access
>to the protected resource, the resource server MUST include the HTTP
>"WWW-Authenticate" response header field

https://tools.ietf.org/html/rfc6750#section-3 (see also https://tools.ietf.org/html/rfc6749#section-5.2)

**Comment by mattiaslevin** [comment]
Fixed
