### ISSUE TITLE
Failed access token responses are missing error codes

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#15]
Failed access token responses are missing error codes.

See https://tools.ietf.org/html/rfc6750#section-3.1 and https://tools.ietf.org/html/rfc6749#section-5.2

**Comment by mattiaslevin** [comment]
Chapter 3.1 relates to adding error codes in the  WWW-Authenticate header when the user try to access a protected resource after they authenticated.

Chapter 5.2 relates to sending back error codes as JSON body if the client credentials fails when accessing oauth methods.

Both are doable.

**Comment by mattiaslevin** [comment]
Following the standard more closely now.
Still some corner cases and having issues returning the WWW-Authenticate header.
