### ISSUE TITLE
Refresh access token request not according to standard

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#16]
Content type ``application/x-www-form-urlencoded`` is not supported when refreshing access tokens, this is required in the OAuth 2.0 standard.

>If the authorization server issued a refresh token to the client, the
>client makes a refresh request to the token endpoint by adding the
>following parameters using the "application/x-www-form-urlencoded"
>format

https://tools.ietf.org/html/rfc6749#section-6

**Comment by mattiaslevin** [comment]
I am making this a duplicate on #13.

I will add form support for all methods in the future (or no one).
