### ISSUE TITLE
Token revocation request not according to standard

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#17]
The token revocation request is not done according to standard. It's using url parameters instead of including parameters in the body using the ``application/x-www-form-urlencoded`` format.

>   The client constructs the request by including the following
>   parameters __using the "application/x-www-form-urlencoded" format in
>   the HTTP request entity-body__:
>
>   token   REQUIRED.  The token that the client wants to get revoked.
>
>   token_type_hint  OPTIONAL.  A hint about the type of the token
>           submitted for revocation...

https://tools.ietf.org/html/rfc7009#section-2.1

**Comment by mattiaslevin** [comment]
Yes.
It will at least be consistent with the other oauth implementations (authorise and refresh) and have the token sent as JSON (not as query parameter).

I will change the implementation to JSON body to start with for consistency.

I will maybe add form-encoded body later, for all methods at the same time.

**Comment by mattiaslevin** [comment]
The same reasoning apply to the validate token request.

**Comment by mattiaslevin** [comment]
Done.

Token revoke is now

```
{
  token: <...>
  token_type_hint: <...>
  client_id: <...>
  client_secret: <...>
}
```
