### ISSUE TITLE
Remove guja-core dependencies to GAE

### ISSUE THREAD

**Issue by sosandstrom** [Wadpam/guja#23]
Would it be possible to remove any dependencies to GAE from guja-core? Can we move those classes to guja-gae if not generalizable?

**Comment by sosandstrom** [comment]
There is a branch dependency/reduceGAE where the dependencies in the pom is removed, but the branch does not build yet.

**Comment by mattiaslevin** [comment]
I do not think we have any direct GAE dependencies in core, I moved out everything.

I noticed that Guava classes sometimes get imported form GAE package if you are not careful when importing.

**Comment by mattiaslevin** [comment]
Ok, all import dependencies removed.
Only MardaoGuicePersistServices.java have dependencies to the Datastore.

I am a bit unsure about the purpose if this services but I do not think it is used.
One option would be:
-Move the Datastore binding to gae (currently in the war file)
-Move MardaoGuicePersistServices.java to gar. Or completely remove.

**Comment by mattiaslevin** [comment]
After some reading and checking the Java doc:

-I moved PersistService and UnitOfWork to the GAE module (slight renaming)
-Moved the binding to Datastore to GAE module as well (if you add the GAE module you are running on the datastore and want the datastore binding in Mardao).

The PersistService and UnitOfWork does not do anything in Mardao-Datastore configuration. You do not need to start/stop the datastore and there is no need to create database sessions.
Right now neither of the classes will ever be called sine the PersistFilter is not configured.

**Comment by sosandstrom** [comment]
Really nice, there are no dependencies to GAE from guja-core nor guja-base.
