### ISSUE TITLE
Update user email

### ISSUE THREAD

**Issue by peoplesbeer** [Wadpam/guja#26]
Currently when a user updates the email address there's no validation email sent etc.

**Comment by mattiaslevin** [comment]
I have started on this one.
Will implement change username at the same time.

**Comment by mattiaslevin** [comment]
Fixed.

Users can not change their emails
/api/user/<userId>email (POST)
{"email":"<newEmail>"}

An email will be sent to the new email. When the user click on the link in the email the new email will be confirmed and replace the old email.
