### ISSUE TITLE
Split OAuth2Resource into one resource per role

### ISSUE THREAD

**Issue by sosandstrom** [Wadpam/guja#8]
Right now, we have mixed the methods of the roles `authorization server` and `federated authorization server` into the same resource, `OAuth2Resource`.
It would be better to split them up, _e.g._
* OAuth2ServerResource
* OAuth2FederatedResource

and make it possible for the application developer to decide which one(s) should be enabled.

Let me know what you think.

**Comment by mattiaslevin** [comment]
That is probably a good idea.
Not sure if there will be any issues with the Rest path (Jersey is not as flexible as Spring).
Will you do it or should I?

**Comment by sosandstrom** [comment]
Fixed.
